### PR TITLE
created db and seeded

### LINKED ISSUE #8: Car Model and Seeds
Car Model
* `make` (str)
* `model`  (str)
* `year` (int)
*  `max_range` (int)

In `db/seeds.rb`, make an entry for every car you want to support.

### PR DESCRIPTION
**Pull request by Daniel-McGlinchy**
closes #8

### CODE REVIEW

**Comment by jeremyamartins** [comment]
I approve this, just waiting on master approval!

**Comment by andyweiss1982** [comment]
This is different from the ERD.  

Can you explain the benefit of this approach?

**Comment by Daniel-McGlinchy** [comment]
> This is different from the ERD. Can you explain the benefit of this approach?
> […](#)
> Sent from my iPhone
> On May 25, 2019, at 6:43 PM, Daniel McGlinchy ***@***.***> wrote: closes #8 You can view, comment on, or merge this pull request online at: #10 Commit Summary created db and seeded File Changes M Gemfile (2) M Gemfile.lock (10) A app/models/car.rb (3) A app/models/make.rb (54) A db/migrate/20190525212347_create_makes.rb (9) A db/migrate/20190525213730_create_cars.rb (11) A db/schema.rb (31) M db/seeds.rb (27) A test/fixtures/cars.yml (11) A test/fixtures/makes.yml (7) A test/models/car_test.rb (7) A test/models/make_test.rb (7) Patch Links: https://github.com/wyncode/C33_daniel_jeremy_loris/pull/10.patch https://github.com/wyncode/C33_daniel_jeremy_loris/pull/10.diff — You are receiving this because your review was requested. Reply to this email directly, view it on GitHub, or mute the thread.

We realized while discussing with a TA that the ERD we originally created would not work for our purposes. There are multiple models for each manufacturer and we want to select by Make then only the Models from that Manufacturer. Below is a revised version of our ERD.

Screenshot from 2019-05-25 21-24-07

If you have any feedback or advise for us in this regard, please let us know.

**Comment by andyweiss1982** [comment]
This implementation is probably fine, but if I’m understanding correctly, every time a new Make comes on to the market you wouldn’t likely want to add a new line of code to the make model.  That sounds like a bit of a code smell to me — although I suppose strictly speaking you wouldn’t need to do this.  

I’m also still not seeing the limitations of the original plan.   Keeping all of the data in one table doesn’t stop you from finding all of the models with a particular make, right?   You would just have to ask for Car.where(make: “Toyota”).  

Lets keep this PR open, it definitely looks like it would get the job done.  But I would like you try and implement the original plan in a separate PR, and then we can discuss the pros and cons of both approaches in greater detail on Tuesday. 

You can probably reuse 90% of the existing seed file (great job on that by the way).

**Comment by Daniel-McGlinchy** [comment]
We just made the changes you suggested and we now have one DB which matches our original ERD.

**Pull request merged**
